name: generate ascii artwork
on: push
jobs:
    build_job1:
        runs-on: ubuntu-latest
        steps:
        - name: checkout-repo
          uses: actions/checkout@v4
        - name: execute shell script with permission
        #without permision you will get error while execution, so permission is mandatory
          run: |
           chmod +x ascii-script.sh
           ./ascii-script.sh
        - name: upload ram text file
          uses: actions/upload-artifact@v7
          with:
            name: my-artifact
            path: ram.txt



    test_job2:
      #by default jobs are runnig in parallel in diff VM and each job runs on its own vm
      #to run jobs in sequential ordeer we use "needs"
      #if a job is dependent on multiple job we can use array(list) also.
      needs: build_job1
      runs-on: ubuntu-latest
      steps:
        - name: download ram text file
          uses: actions/download-artifact@v8
          with:
            name: my-artifact
        - name: test file exists
          run: grep -i "RAM" ram.txt


          
    deploy_job3:
      needs: [test_job2]
      runs-on: ubuntu-latest
      steps:
        - name: download ram text file
          uses: actions/download-artifact@v8
          with:
            name: my-artifact
        - name: read file
          run: cat ram.txt
        