name: generate ascii artwork
on: push
jobs:
    build_job1:
        runs-on: ubuntu-latest
        steps:
        - name: checkout-repo
          uses: actions/checkout@v4
        - name: list repo file
          run: ls -ltra
        - name: execute shell script with permission
        #without permision you will get error while execution, so permission is mandatory
          run: |
           chmod +x ascii-script.sh
           ./ascii-script.sh
    test_job2:
      #by default jobs are runnig in parallel in diff VM and each job runs on its own vm
      #to run jobs in sequential ordeer we use "needs"
      #if a job is dependent on multiple job we can use array(list) also.
      needs: build_job1
      runs-on: ubuntu-latest
      steps:
        - name: sleep for 10secs
          run: sleep 10
        - name: test file exists
          run: grep -i "RAM" ram.txt
    deploy_job3:
      needs: test_job2
      runs-on: ubuntu-latest
      steps:
        - name: deploy
          run: echo Deploying..

        