name: Matrix Configuration

on:
  push:

jobs:
  deploy:
    strategy:
      #samejob->multi os->multi version
      #runs multi job parallely under single job
      matrix:
        os: [ubuntu-latest, ubuntu-20.04, windows-latest]
        images: [hello-world, alpine]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Echo Docker Details
        run: docker info

      - name: Run Image on ${{ matrix.os }}
        run: docker run ${{ matrix.images }}