name: Exploring Variables and Secrets
#env at workflow level
env:
  CONTAINER_REGISTRY: docker.io
  IMAGE_NAME: github-actions-nginx
  #user-name is stored as variable in repo level

on:
  push

jobs:


  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Docker Build
        run: echo docker build -t $CONTAINER_REGISTRY/${{ vars.DOCKER_USERNAME }}/$IMAGE_NAME:latest

      - name: Docker Login
        #password is stored as secret in repo level
        run: echo docker login --username=${{ vars.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Publish
        run: echo docker push $CONTAINER_REGISTRY/${{ vars.DOCKER_USERNAME }}/$IMAGE_NAME:latest

  deploy:
    needs: docker
    runs-on: ubuntu-latest

    steps:
      - name: Docker Run
        run: echo docker run -d -p 8080:80 $CONTAINER_REGISTRY/${{ vars.DOCKER_USERNAME }}/$IMAGE_NAME:latest